### ISSUE TITLE
Am I doing something wrong?

### ISSUE THREAD

**Issue by ericbf** [jbrower95/Explicitor#1]
This doesn't seem to work for me. When I download the .app, it starts as expected. Clicking to create the cache starts as expected as well, but it hangs at a low percentage (0% or 1% in my case).

I also tried to download the .java and using javac to compile it, but javac throws me some errors that prevent compilation :(.

**Comment by jbrower95** [comment]
Here's the problem: i'm compiling using the adobe library ( i forgot what it's called) and for some reason, when i run it through the application packager thing on OSX, it NEVER executes properly. When I compile the code and run the main class, it works fine. But somewhere in the process of making it a .app, it gets broken.
Any thoughts?
Also, the reason the cache wasn't increasing was because the required library wasn't found. If you had an error console open you would've seen repeated errors.
Sorry for the inconvenience, I haven't looked at this in a while but i'll definitely try to fix it.

**Comment by ericbf** [comment]
Would making a .jar work?

**Comment by jbrower95** [comment]
I"m currently trying that. Been trying to for a while :( I can get it to execute and work from the command line but I can't get the jar to compile
